# Note of Measuring String Similarity
## for spelling suggestion?!

မြန်မာစာအတွက် လက်ရှိရှိနေတဲ့ string similarity measurement algorithm တွေက သုံးလို့တော့ရတယ်။  
ဒါပေမဲ့ ငါသိနေတာက လက်ရှိရှိနေတဲ့ algorithm တွေက မြန်မာစာအတွက် perfect မဟုတ်ဘူး။

ရှိပြီးသား နည်းတွေကို အခြေခံပြီးတော့ ငါတို့ မြန်မာစာ အတွက် algorithm အသစ်ရှာလို့ရနိုင်မလား။  
အလွယ်ဆုံးကတော့ algorithm နှစ်မျိုးသုံးမျိုးကို ပေါင်းသုံးတာပဲ။ သို့သော် calculation time ...
တစ်မျိုးထဲသုံးရင်တောင်မှ calculation time ကို ထည့်စဉ်းစားရတယ်။
ဥပမာ စာမျက်နှာ ၁၀ မျက်နှာရှိတဲ့ မြန်မာစာကြောင်းတွေထဲက spelling mistake ရှာတဲ့ case

Similarity or distance measurement က စာလုံးပေါင်းမှားသလား ဆိုတာကိုစစ်တဲ့ နေရာ (spelling detetion) မှာလည်း သုံးနိုင်သလို မှန်နိုင်ချေရှိတဲ့ စာလုံးတွေကို ဆွဲထုတ်တဲ့ နေရာ (spelling suggestion) မှာလည်း သုံးလို့ရတယ်။  

String similarity algorithm တွေက အများကြီးရှိတယ်။  
Algorithm တစ်ခုချင်း၊ တစ်ခုချင်း ရဲ့ အားသာချက်၊ အားနည်းချက်ကိုတော့ အနည်းဆုံး သိမှဖြစ်မယ်။  

Go ahead for exploring some string similarity algorithms ... !   

# Naive Matching

naive distance=0 ဆိုရင် စာကြောင်းနှစ်ကြောင်းက တူတယ်။
Naive matching (or) exact matching စစ်ပုံစစ်နည်း တစ်ခုက

In [1]:
def naive_matching(x, y):
    found = None
    if (len(x) == len(y)):
        found = False
        #print(range(len(y)-len(x)+1))
        for i in range(len(y) - len(x) + 1): # looping over alignments
            found = True
            #print(range(len(x)))
            for j in range(len(x)): # looping over characters
                if y[i+j] != x[j]:
                    print("y[i+j]: ", y[i+j], " x[j]: ", x[j])
                    found = False # မတူရင် alignment လုပ်စရာမလိုတော့ဘူး
                    break
    else:
        print("Error: length of string1 ≠ length of string2!")
        
    return found

In [2]:
naive_matching("ကခဂ", "ကခဂ")

True

In [3]:
naive_matching("ကခဂ", "ကခဃ")

y[i+j]:  ဃ  x[j]:  ဂ


False

In [4]:
naive_matching("ကျောင်းသား", "ကျောင်းသူ")

Error: length of string1 ≠ length of string2!


အဲဒါကို Hamming Distance အတွက် ပြင်ရေးရင်

In [5]:
def naive_Hamming_distance(x, y, maxDistance):
    distance = None
    if (len(x) == len(y)):
        distance = 0
        for i in range(len(y) - len(x) + 1):
            found = True
            for j in range(len(x)):
                print("y[i+j]: ", y[i+j], "x[j]:", x[j])
                if y[i+j] != x[j]:
                    distance += 1
            if distance > maxDistance:
                break
    else:
        print("len(string1) ≠ len(string2)")
    return distance      

In [6]:
naive_Hamming_distance("ကခဂဃ", "ကခဃဂ", 1)

y[i+j]:  က x[j]: က
y[i+j]:  ခ x[j]: ခ
y[i+j]:  ဃ x[j]: ဂ
y[i+j]:  ဂ x[j]: ဃ


2

In [7]:
naive_Hamming_distance("ကခဂဃင", "ကခဂ", 1)

len(string1) ≠ len(string2)


# Hamming Distance

- two input string must be the same length
- only one operation (i.e. substitution)

In [8]:
def hamming_distance(string1, string2): 
    if (len(string1) == len(string2)):
        distance = 0
        common_length = len(string1)
        for i in range(common_length):
            # if two char are different, +1
            if string1[i] != string2[i]:
                distance += 1
        return distance
    else:
        print("Error: length of string1 ≠ length of string2!")

In [9]:
hamming_distance("ကခဂ", "ကဂဂ")

1

In [10]:
hamming_distance("မမဝဝထထက", "မမလှလှထထက")

Error: length of string1 ≠ length of string2!


Hamming distance က word length တူတဲ့ကိစ္စမှာတော့ အသုံးဝင်တယ်

# Levenshtein Distance

In [11]:
from IPython.core.interactiveshell import InteractiveShell
#InteractiveShell.ast_node_interactivity = "all"
InteractiveShell.ast_node_interactivity = "last_expr"


import numpy as np

#ref: http://stackabuse.com/levenshtein-distance-and-text-similarity-in-python/

def levenshtein(seq1, seq2):
    size_x = len(seq1) + 1
    size_y = len(seq2) + 1
    matrix = np.zeros ((size_x, size_y))
    for x in range(size_x):
        matrix [x, 0] = x
    for y in range(size_y):
        matrix [0, y] = y

    for x in range(1, size_x):
        for y in range(1, size_y):
            if seq1[x-1] == seq2[y-1]:
                matrix [x,y] = min(
                    matrix[x-1, y] + 1,
                    matrix[x-1, y-1],
                    matrix[x, y-1] + 1
                )
            else:
                matrix [x,y] = min(
                    matrix[x-1,y] + 1,
                    matrix[x-1,y-1] + 1,
                    matrix[x,y-1] + 1
                )
    print (matrix)
    return (matrix[size_x - 1, size_y - 1])

In [12]:
print(levenshtein("ရဲကျော်သူ", "ရဲကျော်သု"))

[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.  7.  8.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.  6.  7.]
 [ 3.  2.  1.  0.  1.  2.  3.  4.  5.  6.]
 [ 4.  3.  2.  1.  0.  1.  2.  3.  4.  5.]
 [ 5.  4.  3.  2.  1.  0.  1.  2.  3.  4.]
 [ 6.  5.  4.  3.  2.  1.  0.  1.  2.  3.]
 [ 7.  6.  5.  4.  3.  2.  1.  0.  1.  2.]
 [ 8.  7.  6.  5.  4.  3.  2.  1.  0.  1.]
 [ 9.  8.  7.  6.  5.  4.  3.  2.  1.  1.]]
1.0


In [13]:
print(levenshtein("ကခဂဃင", "ကခဂင"))

[[ 0.  1.  2.  3.  4.]
 [ 1.  0.  1.  2.  3.]
 [ 2.  1.  0.  1.  2.]
 [ 3.  2.  1.  0.  1.]
 [ 4.  3.  2.  1.  1.]
 [ 5.  4.  3.  2.  1.]]
1.0


In [14]:
print(levenshtein("ကိုကြီး", "ကိုကျီး"))

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.]
 [ 3.  2.  1.  0.  1.  2.  3.  4.]
 [ 4.  3.  2.  1.  0.  1.  2.  3.]
 [ 5.  4.  3.  2.  1.  1.  2.  3.]
 [ 6.  5.  4.  3.  2.  2.  1.  2.]
 [ 7.  6.  5.  4.  3.  3.  2.  1.]]
1.0


In [15]:
print(levenshtein("ကိုကြီး", "ခိုကြီး"))

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  1.  2.  3.  3.  4.  5.  6.]
 [ 2.  2.  1.  2.  3.  4.  5.  6.]
 [ 3.  3.  2.  1.  2.  3.  4.  5.]
 [ 4.  4.  3.  2.  1.  2.  3.  4.]
 [ 5.  5.  4.  3.  2.  1.  2.  3.]
 [ 6.  6.  5.  4.  3.  2.  1.  2.]
 [ 7.  7.  6.  5.  4.  3.  2.  1.]]
1.0


In [16]:
print(levenshtein("ကိုကြီး", "ကိုဂျီး"))

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.]
 [ 3.  2.  1.  0.  1.  2.  3.  4.]
 [ 4.  3.  2.  1.  1.  2.  3.  4.]
 [ 5.  4.  3.  2.  2.  2.  3.  4.]
 [ 6.  5.  4.  3.  3.  3.  2.  3.]
 [ 7.  6.  5.  4.  4.  4.  3.  2.]]
2.0


In [17]:
print(levenshtein("ကိုကြီး", "ခိုကျီး"))

[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  1.  2.  3.  3.  4.  5.  6.]
 [ 2.  2.  1.  2.  3.  4.  5.  6.]
 [ 3.  3.  2.  1.  2.  3.  4.  5.]
 [ 4.  4.  3.  2.  1.  2.  3.  4.]
 [ 5.  5.  4.  3.  2.  2.  3.  4.]
 [ 6.  6.  5.  4.  3.  3.  2.  3.]
 [ 7.  7.  6.  5.  4.  4.  3.  2.]]
2.0


Algorithm from Michael Gilleland (https://goo.gl/aUYbqW)
** To Do: calculate % of similarity

# We have to understand Dynamic Programming

- Definition of Insert!
- Definition of Delete!
- Definition of Substitute!


# Question: Why taking Minimum instead of Maximum?
# Answer: Try taking Maximum instead of Minimum.

---
## Syllable အတွက် Levenshtein distance ကို တွက်ချင်ရင်
## ဝင်လာတဲ့ စာကြောင်းနှစ်ကြောင်းကို Syllable ဖြတ်ပြီးတော့
## စာကြောင်းနှစ်ခုရဲ့ Syllable တစ်လုံးချင်းစီကို တိုက်စစ်၊ တူရင် 1, မတူရင် 0 ဖြည့်
## ပိုနေတဲ့ syllable (i.e for longer string) တွေကို 0 ဖြည့်ရင်
## Syllable ကို ကိုယ်စားပြုတဲ့ string1, string2 ကို ရပြီ။
## အဲဒီ string နှစ်ခုကို ပုံမှန်အတိုင်း Levenshtein distance တွက်ရင်
## အဲဒီရလဒ်က syllable level Levenshtein distance ပဲ

## ဒီ syllable level က စဉ်းစားသင့်တယ်။
## I know character level only is not enough ...   &
## syllable unit is important for Myanmar language


In [18]:
# Regular Expression Python Library ကို သုံးလို့ရအောင် import လုပ်တာ
import re

# စာလုံးတွေကို အုပ်စုဖွဲ့တာ (သို့) variable declaration လုပ်တာ
# တကယ်လို့ syllable break လုပ်တဲ့ အခါမှာ မြန်မာစာလုံးချည်းပဲ သပ်သပ် လုပ်ချင်တာဆိုရင် enChar က မလိုပါဘူး
myConsonant = "က-အ"
enChar = "a-zA-Z0-9"
otherChar = "ဣဤဥဦဧဩဪဿ၌၍၏၀-၉၊။!-/:-@[-`{-~\s"
ssSymbol = '္'
ngaThat = 'င်'
aThat = '်'

# Regular expression pattern for Myanmar syllable breaking
# *** a consonant not after a subscript symbol AND 
# a consonant is not followed by a-That character or a subscript symbol
# မြန်မာစာကို syllable segmentation လုပ်ဖို့အတွက်က ဒီ RE pattern တစ်ခုတည်းနဲ့ အဆင်ပြေတယ်။
BreakPattern = re.compile(r"((?<!" + ssSymbol + r")["+ myConsonant + r"](?![" + aThat + ssSymbol + r"])" + r"|[" + enChar + otherChar + r"])", re.UNICODE)

# sylbreak function ဆောက်တဲ့ အပိုင်း
def sylbreak(line):
       line = re.sub(r"\s+","", line)
       line = BreakPattern.sub(r" " + r"\1", line)
       return line

In [19]:
sylbreak("မြန်မာစာသည် တို့စာ။ တို့စာကို သုတေသန လုပ်ပါ။")

' မြန် မာ စာ သည် တို့ စာ ။ တို့ စာ ကို သု တေ သ န လုပ် ပါ ။'

In [20]:
# -*- coding: UTF-8 -*-
def syl_check(line1, line2):
    line1_syl = sylbreak(line1)
    line2_syl = sylbreak(line2)
    
    line1_syl = line1_syl.strip()
    line2_syl = line2_syl.strip()
    
    line1_array=line1_syl.split(" ")
    line2_array=line2_syl.split(" ")
    
    #print(line1_array)
    #print(line2_array)
    max_length = max(len(line1_array), len(line2_array))
    min_length = min(len(line1_array), len(line2_array))
    #print(max_length)
    #print(line1_syl)
    #print(min_length)
    #print(line2_syl)
    
    #twod=[[0 for j in range(len(line1_array))] for i in range(len(line2_array))]
    #print(list(set(line1_array) & set(line2_array)))
    
    new_list1 = []
    new_list2 = []
        
    for i in range(max_length):
        #print(i)
        if i < min_length:
            if line1_array[i] == line2_array[i]:
               new_list1.append(1)
               new_list2.append(1)
            else:
                new_list1.append(0)
                new_list2.append(1)
        else:
            new_list1.append(0)
            new_list2.append(1)

    #convertion list into string
    checked_syl_str1 = ''.join(str(e) for e in new_list1)
    checked_syl_str2 = ''.join(str(e) for e in new_list2)
    
    return checked_syl_str1, checked_syl_str2

In [21]:
syl_check("လမင်းကြီး", "နေမင်းကြီး")

('011', '111')

In [22]:
#str1, str2 = syl_check("လမင်းကြီး", "နေမင်းကြီး")
#str1, str2 = syl_check("လှလှပပ", "လှပ")
#str1, str2 = syl_check("လှပ", "လှလှပပ")
#str1, str2 = syl_check("ရှိတယ်", "မရှိ")
#str1, str2 = syl_check("ကခဂ", "ကခဃ") 
#str1, str2 = syl_check("ကခဂဃင", "ကခဂဂဂ")

def char_syl_ld(string1, string2):
    #print input strings
    print("string1:", string1)
    print("string2:", string2)
    
    ld=levenshtein(string1, string2)
    print("Levenshtein distance (character unit): ", ld)
    
    syl_str1, syl_str2 = syl_check(string1, string2)
    print("converted string:", syl_str1)
    print("converted string:", syl_str2)
    syl_ld = levenshtein(syl_str1, syl_str2)
    print("Levenshtein distance (syllable unit):", syl_ld)

In [23]:
char_syl_ld("ဘာပြောတယ်", "ဘပြေတယ်")

string1: ဘာပြောတယ်
string2: ဘပြေတယ်
[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.]
 [ 2.  1.  1.  2.  3.  4.  5.  6.]
 [ 3.  2.  1.  2.  3.  4.  5.  6.]
 [ 4.  3.  2.  1.  2.  3.  4.  5.]
 [ 5.  4.  3.  2.  1.  2.  3.  4.]
 [ 6.  5.  4.  3.  2.  2.  3.  4.]
 [ 7.  6.  5.  4.  3.  2.  3.  4.]
 [ 8.  7.  6.  5.  4.  3.  2.  3.]
 [ 9.  8.  7.  6.  5.  4.  3.  2.]]
Levenshtein distance (character unit):  2.0
converted string: 001
converted string: 111
[[ 0.  1.  2.  3.]
 [ 1.  1.  2.  3.]
 [ 2.  2.  2.  3.]
 [ 3.  2.  2.  2.]]
Levenshtein distance (syllable unit): 2.0


In [24]:
char_syl_ld("ဘာပြောတယ်", "ဘာပြတယ်")

string1: ဘာပြောတယ်
string2: ဘာပြတယ်
[[ 0.  1.  2.  3.  4.  5.  6.  7.]
 [ 1.  0.  1.  2.  3.  4.  5.  6.]
 [ 2.  1.  0.  1.  2.  3.  4.  5.]
 [ 3.  2.  1.  0.  1.  2.  3.  4.]
 [ 4.  3.  2.  1.  0.  1.  2.  3.]
 [ 5.  4.  3.  2.  1.  1.  2.  3.]
 [ 6.  5.  4.  3.  2.  2.  2.  3.]
 [ 7.  6.  5.  4.  3.  2.  3.  3.]
 [ 8.  7.  6.  5.  4.  3.  2.  3.]
 [ 9.  8.  7.  6.  5.  4.  3.  2.]]
Levenshtein distance (character unit):  2.0
converted string: 101
converted string: 111
[[ 0.  1.  2.  3.]
 [ 1.  0.  1.  2.]
 [ 2.  1.  1.  2.]
 [ 3.  2.  1.  1.]]
Levenshtein distance (syllable unit): 1.0


In [25]:
char_syl_ld("ဘာပြောတယ်", "ဘာပတယ်")

string1: ဘာပြောတယ်
string2: ဘာပတယ်
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 1.  0.  1.  2.  3.  4.  5.]
 [ 2.  1.  0.  1.  2.  3.  4.]
 [ 3.  2.  1.  0.  1.  2.  3.]
 [ 4.  3.  2.  1.  1.  2.  3.]
 [ 5.  4.  3.  2.  2.  2.  3.]
 [ 6.  5.  4.  3.  3.  3.  3.]
 [ 7.  6.  5.  4.  3.  4.  4.]
 [ 8.  7.  6.  5.  4.  3.  4.]
 [ 9.  8.  7.  6.  5.  4.  3.]]
Levenshtein distance (character unit):  3.0
converted string: 101
converted string: 111
[[ 0.  1.  2.  3.]
 [ 1.  0.  1.  2.]
 [ 2.  1.  1.  2.]
 [ 3.  2.  1.  1.]]
Levenshtein distance (syllable unit): 1.0


# How about Cosine Similarity?

Cosine similarity က အရမ်းအသုံးဝင်တာ ငါသိတယ်။  
ဒါပေမဲ့ စာကြောင်းတိုတွေအတွက်၊ စာကြောင်း နှစ်ကြောင်းတည်းကိုပဲ cosine similarity တိုင်းလို့တော့ မဖြစ်နိုင်ဘူး။  
Corpus level, Dictionary level သွားမှ ဖြစ်မယ်။  
စာလုံးတွေကို တန်ဖိုးတစ်ခုပြောင်းတဲ့ ကိစ္စကို စဉ်းစားရမယ်လို့ ဆိုလိုတာ

အလွယ်ဆုံးကတော့ character level measurement 

*** Spelling Checking မှာက တကယ်တမ်း ငါတို့ စဉ်းစားရမှာ က အနည်းဆုံး phrase level ...


In [26]:
from math import sqrt

def text2vectors(string12):
    def vectorize(sentence, vocab):
        return [sentence.split().count(i) for i in vocab]
    vectorized_text = []
    vocab = sorted(set(chain(*[i.lower().split() for i in string12])))
    
    for i in string12:
        vectorized_text.append((i, vectorize(i, vocab)))
    return vectorized_text, vocab

def create_vectorizedText_vocab(string1, string2):

    string12 = [string1, string2]
    vectorized_text, vocab = text2vectors(string12)
    return vectorized_text, vocab

def cosine_similarity(u, v):
    return np.dot(u,v) / (sqrt(np.dot(u,u)) * sqrt(np.dot(v,v)))

def cos_sim(a, b):
    """Takes 2 vectors a, b and returns the cosine similarity according 
    to the definition of the dot product"""
    dot_product = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot_product / (norm_a * norm_b)


In [27]:
from itertools import chain, product

def calc_cosine_similarity(string1, string2):
    # စာကြောင်းနှစ်ကြောင်းကို vector ဆောက်တယ်။ vocabulary list လည်းပြင်ဆင်တယ်။
    vt, vocab = create_vectorizedText_vocab(string1, string2)
    print("vt:", vt)

    for stringX, stringY in product(vt, vt):
        print(stringX[0])
        print(stringY[0])
        print("Cosine similarity value =", cosine_similarity(stringX[1], stringY[1]))
        
calc_cosine_similarity("နေကောင်းပါတယ်နော်။", "နေကောင်းပါတယ်ရှင်။")
print("=====")
calc_cosine_similarity("နေကောင်းပါတယ်နော်။", "သိပ်နေမကောင်းပါဘူးရှင့်။")
print("=====")
calc_cosine_similarity("နေကောင်းပါတယ်နော်။", "ကောင်းပါတယ်ရှင်။")

# We have to make word segmentation
print("\n We have to make word segmentation ... \n")
calc_cosine_similarity("နေကောင်း ပါတယ် နော် ။", "နေကောင်း ပါတယ် ရှင် ။")
print("=====")
calc_cosine_similarity("နေကောင်း ပါတယ် နော် ။", "သိပ် နေ မကောင်း ပါဘူး ရှင့် ။")
print("=====")
calc_cosine_similarity("နေကောင်း ပါတယ် နော် ။", "ကောင်း ပါတယ် ရှင် ။")
print("=====")
calc_cosine_similarity("ကောင်းဘူး", "ဘာ")

#calc_cosine_similarity("နေကောင်း ပါတယ် နော် ။ အရင်က ထက်တော့", "နေကောင်းပါတယ်ရှင်။")
#calc_cosine_similarity("နေကောင်းပါတယ်နော်။", "နေကောင်းပါတယ်ရှင်။")

vt: [('နေကောင်းပါတယ်နော်။', [1, 0]), ('နေကောင်းပါတယ်ရှင်။', [0, 1])]
နေကောင်းပါတယ်နော်။
နေကောင်းပါတယ်နော်။
Cosine similarity value = 1.0
နေကောင်းပါတယ်နော်။
နေကောင်းပါတယ်ရှင်။
Cosine similarity value = 0.0
နေကောင်းပါတယ်ရှင်။
နေကောင်းပါတယ်နော်။
Cosine similarity value = 0.0
နေကောင်းပါတယ်ရှင်။
နေကောင်းပါတယ်ရှင်။
Cosine similarity value = 1.0
=====
vt: [('နေကောင်းပါတယ်နော်။', [1, 0]), ('သိပ်နေမကောင်းပါဘူးရှင့်။', [0, 1])]
နေကောင်းပါတယ်နော်။
နေကောင်းပါတယ်နော်။
Cosine similarity value = 1.0
နေကောင်းပါတယ်နော်။
သိပ်နေမကောင်းပါဘူးရှင့်။
Cosine similarity value = 0.0
သိပ်နေမကောင်းပါဘူးရှင့်။
နေကောင်းပါတယ်နော်။
Cosine similarity value = 0.0
သိပ်နေမကောင်းပါဘူးရှင့်။
သိပ်နေမကောင်းပါဘူးရှင့်။
Cosine similarity value = 1.0
=====
vt: [('နေကောင်းပါတယ်နော်။', [0, 1]), ('ကောင်းပါတယ်ရှင်။', [1, 0])]
နေကောင်းပါတယ်နော်။
နေကောင်းပါတယ်နော်။
Cosine similarity value = 1.0
နေကောင်းပါတယ်နော်။
ကောင်းပါတယ်ရှင်။
Cosine similarity value = 0.0
ကောင်းပါတယ်ရှင်။
နေကောင်းပါတယ်နော်။
Cosine similarity value = 0.0
ကောင်းပါတ

# We have to consider consistency of word segmentation

- Character level မဟုတ်ပဲ word level ဆိုရင်တော့ မြန်မာစာလုံးတွေကို အားလုံးညီနေအောင် segmentation လုပ်ထားမှ ဖြစ်မယ်။   
မဟုတ်ရင် ပြဿနာရှိတယ်။  

- Syllable level ဆိုရင်တော့ ငါတို့ consistency ကို control လုပ်လို့ရလိမ့်မယ်။ 

# Cosine Similarity with Syllable Segmentation

မြန်မာစာကို syllable segmentation ဖြတ်ပြီးမှ Cosine similarity တိုင်းကြည့်ရင်ကော  
ရလဒ်က ဘယ်လိုနေမလဲ။  

In [28]:
# Comparing between word level and syllable level cosine similarity

def calc_cosine_similarity_laconic(string1, string2):
    # စာကြောင်းနှစ်ကြောင်းကို vector ဆောက်တယ်။ vocabulary list လည်းပြင်ဆင်တယ်။
    vt, vocab = create_vectorizedText_vocab(string1, string2)
    print("vt:", vt)
    print("Cosine similarity value =", cosine_similarity(vt[0][1], vt[1][1]))
        
print("\n We have to make word segmentation ... \n")
calc_cosine_similarity_laconic("နေကောင်း ပါတယ် နော် ။", "နေကောင်း ပါတယ် ရှင် ။")
print("=====")
calc_cosine_similarity_laconic("နေကောင်း ပါတယ် နော် ။", "သိပ် နေ မကောင်း ပါဘူး ရှင့် ။")
print("=====")
calc_cosine_similarity_laconic("နေကောင်း ပါတယ် နော် ။", "ကောင်း ပါတယ် ရှင် ။")

print("\n How about syllable segmentation? \n")
str1_syl = sylbreak("နေကောင်းပါတယ်နော်။")
str2_syl = sylbreak("နေကောင်းပါတယ်ရှင်။")

calc_cosine_similarity_laconic(str1_syl, str2_syl)
print("=====")

str1_syl = sylbreak("နေကောင်းပါတယ်နော်။")
str2_syl = sylbreak("သိပ်နေမကောင်းပါဘူးရှင့်။")
calc_cosine_similarity_laconic(str1_syl, str2_syl)
print("=====")

str1_syl = sylbreak("နေကောင်းပါတယ်နော်။")
str2_syl = sylbreak("ကောင်းပါတယ်ရှင်။")
calc_cosine_similarity_laconic(str1_syl, str2_syl)



 We have to make word segmentation ... 

vt: [('နေကောင်း ပါတယ် နော် ။', [1, 1, 1, 0, 1]), ('နေကောင်း ပါတယ် ရှင် ။', [1, 0, 1, 1, 1])]
Cosine similarity value = 0.75
=====
vt: [('နေကောင်း ပါတယ် နော် ။', [0, 1, 1, 1, 0, 0, 0, 0, 1]), ('သိပ် နေ မကောင်း ပါဘူး ရှင့် ။', [1, 0, 0, 0, 1, 1, 1, 1, 1])]
Cosine similarity value = 0.204124145232
=====
vt: [('နေကောင်း ပါတယ် နော် ။', [0, 1, 1, 1, 0, 1]), ('ကောင်း ပါတယ် ရှင် ။', [1, 0, 0, 1, 1, 1])]
Cosine similarity value = 0.5

 How about syllable segmentation? 

vt: [(' နေ ကောင်း ပါ တယ် နော် ။', [1, 1, 1, 1, 1, 0, 1]), (' နေ ကောင်း ပါ တယ် ရှင် ။', [1, 1, 1, 0, 1, 1, 1])]
Cosine similarity value = 0.833333333333
=====
vt: [(' နေ ကောင်း ပါ တယ် နော် ။', [1, 1, 1, 1, 1, 0, 0, 0, 0, 1]), (' သိပ် နေ မ ကောင်း ပါ ဘူး ရှင့် ။', [1, 0, 1, 0, 1, 1, 1, 1, 1, 1])]
Cosine similarity value = 0.57735026919
=====
vt: [(' နေ ကောင်း ပါ တယ် နော် ။', [1, 1, 1, 1, 1, 0, 1]), (' ကောင်း ပါ တယ် ရှင် ။', [1, 1, 0, 0, 1, 1, 1])]
Cosine similarity value = 0.73029674334


# Comparing with Sklearn's cosine_similarity

In [29]:
import sklearn.metrics
sklearn_cosine = sklearn.metrics.pairwise.cosine_similarity

str1_syl = sylbreak("နေကောင်းပါတယ် နာ်။")
str2_syl = sylbreak("သိပ်နေမကောင်းပါဘူးရှင့်။")
calc_cosine_similarity_laconic(str1_syl, str2_syl)

vt, vocab = create_vectorizedText_vocab(str1_syl, str2_syl)
print("vt:", vt)
 
# for confirmation
#print("binary_str1:", vt[0][1])
#print("binary_str1:", vt[1][1])
#print("type, vt[0][1]:", type(vt[0][1]))

#change into np.array
bin_str1 = np.array([vt[0][1]])
bin_str2 = np.array([vt[1][1]])

#for confirmation
#print("bin_str1:", bin_str1)
#print("bin_str2:", bin_str2)
#print("type:", type(bin_str1))

cosine_sim_score = sklearn_cosine(bin_str1, bin_str2)
cosine_sim_score = cosine_sim_score.tolist()[0]
print(cosine_sim_score[0])
print("=====")

str1_syl = sylbreak("နေကောင်းပါတယ်နော်။")
str2_syl = sylbreak("ကောင်းပါတယ်ရှင့်။")
calc_cosine_similarity_laconic(str1_syl, str2_syl)

vt, vocab = create_vectorizedText_vocab(str1_syl, str2_syl)
print("vt:", vt)
cosine_sim_score = sklearn_cosine(bin_str1, bin_str2)
cosine_sim_score = cosine_sim_score.tolist()[0]

print(cosine_sim_score[0])

vt: [(' နေ ကောင်း ပါ တယ် နာ် ။', [1, 1, 1, 1, 1, 0, 0, 0, 0, 1]), (' သိပ် နေ မ ကောင်း ပါ ဘူး ရှင့် ။', [1, 0, 0, 1, 1, 1, 1, 1, 1, 1])]
Cosine similarity value = 0.57735026919
vt: [(' နေ ကောင်း ပါ တယ် နာ် ။', [1, 1, 1, 1, 1, 0, 0, 0, 0, 1]), (' သိပ် နေ မ ကောင်း ပါ ဘူး ရှင့် ။', [1, 0, 0, 1, 1, 1, 1, 1, 1, 1])]
0.5773502691896258
=====
vt: [(' နေ ကောင်း ပါ တယ် နော် ။', [1, 1, 1, 1, 1, 0, 1]), (' ကောင်း ပါ တယ် ရှင့် ။', [1, 1, 0, 0, 1, 1, 1])]
Cosine similarity value = 0.73029674334
vt: [(' နေ ကောင်း ပါ တယ် နော် ။', [1, 1, 1, 1, 1, 0, 1]), (' ကောင်း ပါ တယ် ရှင့် ။', [1, 1, 0, 0, 1, 1, 1])]
0.5773502691896258


# Ngram Similarity

In [30]:
def ngrams(sentence, n):
    return list(zip(*[sentence.split()[i:] for i in range(n)]))

def test_ngrams(string1, string2):
    # စာကြောင်းနှစ်ကြောင်းကို vector ဆောက်တယ်။ vocabulary list လည်းပြင်ဆင်တယ်။
    vt, vocab = create_vectorizedText_vocab(string1, string2)
    for string_i in vt:
        print(string_i[0])
        print(ngrams(string_i[0], 2))
        print(ngrams(string_i[0], 3))


In [31]:
print("\n ngram list of word segmentation ... \n")
test_ngrams("နေကောင်း ပါတယ် နော် ။", "နေကောင်း ပါတယ် ရှင် ။")

print("=====")
test_ngrams("နေကောင်း ပါတယ် နော် ။", "သိပ် နေ မကောင်း ပါဘူး ရှင့် ။")
print("=====")
test_ngrams("နေကောင်း ပါတယ် နော် ။", "ကောင်း ပါတယ် ရှင် ။")

print("\n How about ngram list with syllable segmentation? \n")
str1_syl = sylbreak("နေကောင်းပါတယ်နော်။")
str2_syl = sylbreak("နေကောင်းပါတယ်ရှင်။")

test_ngrams(str1_syl, str2_syl)
print("=====")

str1_syl = sylbreak("နေကောင်းပါတယ်နော်။")
str2_syl = sylbreak("သိပ်နေမကောင်းပါဘူးရှင့်။")
test_ngrams(str1_syl, str2_syl)
print("=====")

str1_syl = sylbreak("နေကောင်းပါတယ်နော်။")
str2_syl = sylbreak("ကောင်းပါတယ်ရှင်။")
test_ngrams(str1_syl, str2_syl)


 ngram list of word segmentation ... 

နေကောင်း ပါတယ် နော် ။
[('နေကောင်း', 'ပါတယ်'), ('ပါတယ်', 'နော်'), ('နော်', '။')]
[('နေကောင်း', 'ပါတယ်', 'နော်'), ('ပါတယ်', 'နော်', '။')]
နေကောင်း ပါတယ် ရှင် ။
[('နေကောင်း', 'ပါတယ်'), ('ပါတယ်', 'ရှင်'), ('ရှင်', '။')]
[('နေကောင်း', 'ပါတယ်', 'ရှင်'), ('ပါတယ်', 'ရှင်', '။')]
=====
နေကောင်း ပါတယ် နော် ။
[('နေကောင်း', 'ပါတယ်'), ('ပါတယ်', 'နော်'), ('နော်', '။')]
[('နေကောင်း', 'ပါတယ်', 'နော်'), ('ပါတယ်', 'နော်', '။')]
သိပ် နေ မကောင်း ပါဘူး ရှင့် ။
[('သိပ်', 'နေ'), ('နေ', 'မကောင်း'), ('မကောင်း', 'ပါဘူး'), ('ပါဘူး', 'ရှင့်'), ('ရှင့်', '။')]
[('သိပ်', 'နေ', 'မကောင်း'), ('နေ', 'မကောင်း', 'ပါဘူး'), ('မကောင်း', 'ပါဘူး', 'ရှင့်'), ('ပါဘူး', 'ရှင့်', '။')]
=====
နေကောင်း ပါတယ် နော် ။
[('နေကောင်း', 'ပါတယ်'), ('ပါတယ်', 'နော်'), ('နော်', '။')]
[('နေကောင်း', 'ပါတယ်', 'နော်'), ('ပါတယ်', 'နော်', '။')]
ကောင်း ပါတယ် ရှင် ။
[('ကောင်း', 'ပါတယ်'), ('ပါတယ်', 'ရှင်'), ('ရှင်', '။')]
[('ကောင်း', 'ပါတယ်', 'ရှင်'), ('ပါတယ်', 'ရှင်', '။')]

 How about ngram list with syllable s

Note:

Once the unique n-grams for the term pair have been identified and counted, a quantitative similarity measure S between them can be computed in a number of ways, e.g., by using the Dice coefficient or the Overlap coefficient as follows.  

Dice coefficient: S = 2C/(A+B)  

Overlap coefficient: S = C/min(A,B)  

where A is the number of unique n-grams in the first term, B the number of unique n-
grams in the second term, and C the number of unique n-grams shared by both of them.


# To Do: Comparing Levenshtein Distance, Cosine Distance, Damerau-Levenshtein Distance, Jaro-Winkler Score and ngram Distance



In [32]:
#tr1_syl = sylbreak("နေကောင်းပါတယ်နော်။")
#str2_syl = sylbreak("ကောင်းပါတယ်ရှင်။")
str1 = "ကျွန်တော်က"
str2 = "ကြွန်တော်ကို"

print("Levenshtein Distance:")
print(levenshtein(str1, str2))

print("Cosine Similarity:")
calc_cosine_similarity_laconic(sylbreak(str1), sylbreak(str2))

dist = distance_unigrams_same(str1, str2)
print("unigrams distance of str1, str2:", dist)
dist = distance_bigrams_same(str1, str2)
print("bigrams distance of str1, str2:", dist)
dist = distance_trigrams_same(str1, str2)
print("trigrams distance of str11, str22:", dist)
print("==========")

str1 = "ကျွန် တော် က"
str2 = "ကြွန် တော် ကို"

print("Levenshtein Distance:")
print(levenshtein(str1, str2))

print("Cosine Similarity:")
calc_cosine_similarity_laconic(sylbreak(str1), sylbreak(str2))

dist = distance_unigrams_same(str1, str2)
print("unigrams distance of str1, str2:", dist)
dist = distance_bigrams_same(str1, str2)
print("bigrams distance of str1, str2:", dist)
dist = distance_trigrams_same(str1, str2)
print("trigrams distance of str11, str22:", dist)

print("==========")

str1 = "ကျွန်တော်ကားကအနီရောင်"
str2 = "ကြွန်တော်ကိုအနီရောင်ကြယ်ပေးပါ"

print("Levenshtein Distance:")
print(levenshtein(str1, str2))

print("Cosine Similarity:")
calc_cosine_similarity_laconic(sylbreak(str1), sylbreak(str2))

dist = distance_unigrams_same(str1, str2)
print("unigrams distance of str1, str2:", dist)
dist = distance_bigrams_same(str1, str2)
print("bigrams distance of str1, str2:", dist)
dist = distance_trigrams_same(str1, str2)
print("trigrams distance of str1, str2:", dist)
print("==========")

str1 = "ကျွန် တော် ကား က အ နီ ရောင်"
str2 = "ကြွန် တော် ကို အ နီ ရောင် ကြယ် ပေး ပါ"

print("Levenshtein Distance:")
print(levenshtein(str1, str2))

print("Cosine Similarity:")
calc_cosine_similarity_laconic(sylbreak(str1), sylbreak(str2))

dist = distance_unigrams_same(str1, str2)
print("unigrams distance of str1, str2:", dist)
dist = distance_bigrams_same(str1, str2)
print("bigrams distance of str1, str2:", dist)
dist = distance_trigrams_same(str1, str2)
print("trigrams distance of str1, str2:", dist)

Levenshtein Distance:
[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.]
 [  1.   0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]
 [  2.   1.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.]
 [  3.   2.   2.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
 [  4.   3.   3.   2.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [  5.   4.   4.   3.   2.   1.   2.   3.   4.   5.   6.   7.   8.]
 [  6.   5.   5.   4.   3.   2.   1.   2.   3.   4.   5.   6.   7.]
 [  7.   6.   6.   5.   4.   3.   2.   1.   2.   3.   4.   5.   6.]
 [  8.   7.   7.   6.   5.   4.   3.   2.   1.   2.   3.   4.   5.]
 [  9.   8.   8.   7.   6.   5.   4.   3.   2.   1.   2.   3.   4.]
 [ 10.   9.   9.   8.   7.   6.   5.   4.   3.   2.   1.   2.   3.]]
3.0
Cosine Similarity:
vt: [(' ကျွန် တော် က', [1, 0, 1, 0, 1]), (' ကြွန် တော် ကို', [0, 1, 0, 1, 1])]
Cosine similarity value = 0.333333333333


NameError: name 'distance_unigrams_same' is not defined

# Testing with Korean (한글) Words

I will used two Korean word pairs, (1) 국어 and 숙어 (2) 나무가지 and 나뭇가지.  

Here,  
   "국어" (national language)  
   "숙어"(phrase)  
   
   "나무가지" (tree branch: old spelling standard)  
   "나뭇가지" (tree branch: new spelling standard)  
   
For typing Korean characters, I used following online keyboard:  
https://www.lexilogos.com/keyboard/korean.htm  


In [ ]:
ko_str1 = "국어"
ko_str2 = "숙어"

print("ko_str1: ", ko_str1)
print("ko_str2: ", ko_str2, "\n")
print("Levenshtein Distance:")
print(levenshtein(ko_str1, ko_str2))

print("==========")

print("For ngram distance calculation:")
dist = distance_unigrams_same(ko_str1, ko_str2)
print("unigrams distance of ko_str1, ko_str2:", dist)
print("")

ko_str1 = "국 어"
ko_str2 = "숙 어"

print("ko_str1: ", ko_str1)
print("ko_str2: ", ko_str2, "\n")


dist = distance_bigrams_same(ko_str1, ko_str2)
print("bigrams distance of ko_str1, ko_str2:", dist)
dist = distance_trigrams_same(ko_str1, ko_str2)
print("trigrams distance of str1, str2:", dist)
print("==========")

print("\n2nd Case:")
ko_str1 = "나무가지"
ko_str2 = "나뭇가지"

print("ko_str1: ", ko_str1)
print("ko_str2: ", ko_str2, "\n")
print("Levenshtein Distance:")
print(levenshtein(ko_str1, ko_str2))
print("==========")
print("For ngram distance calculation:")

dist = distance_unigrams_same(ko_str1, ko_str2)
print("unigrams distance of ko_str1, ko_str2:", dist)
print("")

ko_str1 = "나 무 가 지"
ko_str2 = "나 뭇 가 지"

print("ko_str1: ", ko_str1)
print("ko_str2: ", ko_str2, "\n")

dist = distance_bigrams_same(ko_str1, ko_str2)
print("bigrams distance of ko_str1, ko_str2:", dist)
dist = distance_trigrams_same(ko_str1, ko_str2)
print("trigrams distance of str1, str2:", dist)


Reference Paper1: Edit Distance Calculation by Phonetic Rules and Word-length
Normalization, Byunggul Bae, Seung-Shik Kang, Byung-Yeon Hwang  

Reference Paper2: Word Similarity Calculation by Using the Edit Distance
Metrics with Consonant Normalization, Seung-Shik Kang, 2015  

အထက်ပါ စာတမ်းနှစ်စောင်ထဲမှာ ပြောပြထားသလို case နှစ်ခုစလုံးအတွက် edit distance က 1 ဖြစ်နေတယ်။   
သူတို့ပေပါထဲမှာ ရေးထားတဲ့ 0.5 ဖြစ်သင့်တယ်၊ ထားချင်တယ်ဆိုတဲ့ အချက်ကို ငါရပြီ။  


Proposal တစ်ခုက "Edit Distance Normalization"


$$ N = \frac{\alpha}{ \max(\vert W_{1} \vert, \  \vert W_{2} \vert)} $$  

Where, $$ \vert W_{i} \vert = 3 \times syllable\_length(W_{i}) $$


for case 1:

ko_str1:  국 어  
ko_str2:  숙 어 

$$ N = \frac{1}{ \max(\vert 3 \times 2 \vert, \  \vert 3 \times 2 \vert)} $$  
$$ N = \frac{1}{ \max(\vert 6 \vert, \  \vert 6 \vert)} $$  
$$ N = \frac{1}{6} $$
$$ N = 0.16 $$

for case 2:

ko_str1:  나무가지  
ko_str2:  나뭇가지 

$$ N = \frac{1}{ \max(\vert 3 \times 4 \vert, \  \vert 3 \times 4 \vert)} $$  
$$ N = \frac{1}{12} $$
$$ N = 0.08 $$  


ဒီ ပရိုပိုဇယ်နဲ့ဆိုရင် အထက်ပါ case (1), case (2) မှာဆိုရင် ရှည်တဲ့စာကြောင်းက ပိုပြီးတော့ similarity ဖြစ်တယ်။  

ဒီစာတမ်း ၂စောင် ကို အခြေခံပြီ: မြန်မာစာအတွက် detail study လုပ်သင့်တာက  

1. Character based Edit Distance (FIN)
2. Syllable based Edit Distance (FIN)
3. Character and Syllable based Edit Distance, (i.e. Hybrid) (Not yet)
4. Normalized Phoneme based Edit Distance (Not yet)
5. Normalized Phoneme and Normalized Edit Distance (Not yet)

----

No. 3 က လုပ်လို့ရတယ်။ Error syllable ကို char level calculation လုပ်ပြီး၊ တခြား စာလုံးတွေက syllable level edit distance တွက်တာလို့ နားလည်တယ်။  
No. 4 က မြန်မာစာအတွက် စဉ်းစားရမယ်။ သရအတွက် normalization လား။  
No. 5 approach ကတော့ No. 4 ပြီးမှပဲ လုပ်လို့ရမယ်။    

In [ ]:
#calculating average of list elememt values

def average_calc(numbers):
    try:
        avg = sum(numbers)/len(numbers)
        print("= ", sum(numbers), "/", len(numbers))  
        return avg
    except ZeroDivisionError:
        return "Zero Division Error!"

In [ ]:
average([1, 2, 3, 4, 5])
average([])

# Damerau-Levenshtein Distance (DLD)

DLD ကို တွက်ကြည့်ရန်


Euclidean: Take the square root of the sum of the squares of the differences of the coordinates.

For example, if x=(a,b) and y=(c,d), the Euclidean distance between x and y is

(a−c)2+(b−d)2‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾√.

Manhattan: Take the sum of the absolute values of the differences of the coordinates.

For example, if x=(a,b) and y=(c,d), the Manhattan distance between x and y is

|a−c|+|b−d|.

For your vectors, it's the same thing except you have more coordinates.

# Jaro-Winkler Score Calculation 

မြန်မာစာအတွက် Jaro-Winkler Score ကို တွက်ကြည့်ရင်ကော

# Distance of Consonants + Distance of Vowels

ဗျည်း အတွက် distance ကို သပ်သပ်တိုင်းပြီး  
သရတွေ အတွက် distance ကို သပ်သပ် တိုင်းတာမျိုး ကော လုပ်လို့ရမလား။ အသုံးဝင်မလား။  

# Vowel Combination or Phoneme Similarity

Word or String Similarity အတွက် အသံထွက်ကိုလည်း ထည့်သွင်းစဉ်းစားလို့ ရတယ်။  
ဒါပေမဲ့ ငါလုပ်ခဲ့တဲ့ Grapheme to Phoneme experiment တွေကနေ ငါနားလည်ခဲ့တာက  
ငါတို့ မြန်မာစာမှာက ရေးတော့အမှန် ဖတ်တော့အသံ ဆိုတဲ့ကိစ္စက ဖြေရှင်းရတာ မလွယ်ဘူး။

အသံဆိုတာထက်၊ Vowel combination ကိုပဲ စဉ်းစားရင်ကော  
ဆိုလိုတာက သရတွဲတွေကိုပဲ တိုက်စစ်ပြီး ဘယ်လောက်တူသလဲ similarity score ထုတ်တဲ့ကိစ္စ  
*** ရေးတဲ့အသံကိုပဲ ယူစဉ်းစားတဲ့ ပုံစံ

==========

ျ၊ ြ
ရ၊ ယ
က၊ ဂ
စ၊ ဆ
လ၊ ဠ
န၊ ဏ

ငါ့ရဲ့ kKg keyboard mapping ပဲ

==========

Phonetic similarity paper တွေကို ပြန်ဖတ်ရန်။ ဒီကြားထဲမှာ စာတမ်းအသစ်တွေလည်း ရှိနိုင်တယ်။  

==========


# Similarity with Word2Vec

ဒီနည်းကတော့ Corpus အပေါ်ကို မူတည်နေတယ်။  
ကောင်းတာက meaning ဆိုတဲ့ concept က ပါဝင်တဲ့ ကိစ္စ။ သို့သော် လက်ရှိပြောနေကြတဲ့ meaning မှာက ပြဿနာတွေရှိသေးတယ်။  
Meaning similarity ကို spelling checking အတွက် ထည့်စဉ်းစားပေးနိုင်ရင်တော့ intelligent ဖြစ်တယ်။  
ငါသိရသလောက် လက်ရှိ string similarity တွေမှာက meaning ကို လုံးဝထည့်မစဉ်းစားထားကြဘူး။  



# Similarity with Syl2Vec for Myanmar Language

ဒါကတော့ Myanmar specific approach ဖြစ်သွားလိမ့်မယ်။  
တခုကောင်းတာက UCSY Corpus လောက်ရှိရင်ကို အတိုင်းအတာတစ်ခုအထိ Syllable similarity ကို တိုင်းတာလို့ ရပြီ။  
ဒီ similarity က syllable ngram ထက် ဘယ်လောက်သာမှာလဲ။  
Syllable meaning လား။  


# Study on Myanmar Language Spelling Examples

Followings are some spelling mistakes that I took from email, BBC and VOA news:

- အဘိဓာန်အ<span style="color:red">ပိုင်</span>ကိုကော update လုပ်ထားသေးလား။ 

- အဲဒီ ဒေသမှာ နေသူတွေကတော့ ကာကွယ်ရေး ဝန်ကြီးရဲ့ ပြောဆို မှု ကို လက်မခံပါဘူး။ အစိုးရ နဲ့ ကယ်ဆယ်ရေး အဖွဲ့တွေက <span style="color:red">ပြစ်</span>ထား လို့ သူတို့ အနေနဲ့ ဒီလို ကြုံတွေ့ ရတာ ဆိုပြီး ဒေါသတကြီး ပြန်လည် တုန့်ပြန် ကြပါတယ်။ 

- တရုတ်က မြန်မာနိုင်ငံကို သုံးပြီးတော့ အိန္ဒိသမုဒ္ဒရာကို ကြီး<span style="color:red">ဆိုး</span>လာနိုင်တယ်ဆိုတဲ့ မဟာဗျူဟာ ပြဿနာပေါ့။ ဒါကို Trump အစိုးရက ဂရုမစိုက်ဘူးဆိုတဲ့ သဘောလား။  

- မိုးဒဏ် အပြင်းအထန်ခံစားခဲ့ရသူတွေကို ချက်ခြင်း ငွေကြေးထောက်ပံ့ဖို့နဲ့ ဆေးဝါး ကုသမှုခံယူဖို့ လိုအပ်နေသူ တွေကို အကူအညီတွေပေးရေး လမ်းညွှန်ချက်ကို လည်း <span style="color:red">ထုန်</span>ပြန်လိုက်တယ်လို့လည်း ပြောခွင့်ရက ဆိုပါတယ်။ 

- ကျနော်တို့ဘဝမှာ တသက်လုံးကမကြားတဲ့ တရားရုံးအမိန့်တွေလည်း ကြားနေရတယ်၊ ဒါတွေက လုံးဝမဖြစ်သင့်ဘူး ။ အမှုလိုက်<span style="color:red">ခဲ</span>တာ နှစ်ပေါင်းမနည်းဘူး၊ ဒီဟာမျိုး အမိန့်မျိုး တခါမှမကြားဖူးသေးဘူး။  

- လတ်တ<span style="color:red">လာ</span>ကာလအတွင်း နိုင်ငံတဝန်းဖြစ်ပွားနေတဲ့ ရေကြီး မြေပြိုမှုတွေကြောင့် ပြီးခဲ့တဲ့ ဇူလိုင်လ ၂၉ ရက်နေ့အထိ ၁၀ ဦး သေဆုံးခဲ့ပြီးဖြစ်တယ်လို့ ပြည်တွင်းသတင်းတွေမှာ ဖော်ပြနေပါတယ်။  

- ဒီလို ဗိုလ်ချုပ်အောင်ဆန်း ကြေးရုပ်နဲ့ ပတ်သတ်လို့ ကန့်ကွက်တဲ့ ကယား ပြည်နယ် က ကရင်နီလူငယ်များ သမ<span style="color:red">ဂ</span> အပါအဝင် အဖွဲ့တွေက လူငယ် ၂၃ယောက် ကို ပြည်နယ်အစိုးရက တရားစွဲဆိုထားပြီး လေးယောက်ကတော့ အခုလက်ရှိ လွိုင်ကော်အကျဉ်းထောင်ထဲမှာ ဖမ်းဆီးထားပါတယ်။  

- “ဒေသတွင်း <span style="color:red">နိ်ုင်</span>ငံတိုင်းက သူတို့ရေနံကို ရောင်းနေကြပြီး ကျနော်တို့က ဘာမှမလုပ်ဘဲ ထိုင်ကြည့်နေဖို့ဆိုတာ ဖြစ်နိုင်ပါသလား၊ သမိုင်းတလျှောက် ဒီရေလမ်းကြောင်း လုံခြုံရေးကို ကျနော်တို့ ထိန်းသိမ်းလာတာဆိုတာ မမေ့ပါနဲ့၊ ရေနံသယ်ပို့ လမ်းကြောင်း လုံခြုံရေးကို သမိုင်းနဲ့ချီပြီး ကျနော်တို့လုပ်လာတာပါ၊ ဒါကိုမမေ့ပါနဲ့” လို့ သမ္မတ Rouhani ကပြောပါတယ်။  

- ဂျပန်နိုင်ငံမှာ စံချိန်တင်လောက်တဲ့ အပူလှိုင်းဖြတ်သန်းတာကြောင့် လူပေါင်း ၃၀ လောက်သေဆုံးပြီး ထောင်နဲ့ချီတဲ့ လူတွေလည်း အပူလှိုင်းဒဏ်ခံစားရတာကြောင့် နိုင်ငံတဝှမ်းက ဆေးရုံတွေ<span style="color:red">စီ</span> တက်ရောက်ပြီး ကုသမှုခံယူနေပါတယ်။  

- လိုဏ်ဂူထဲမှာ သီတင်းနှစ်ပတ်ကျော်ကြာ <span style="color:red">ပိ်တ်</span>မိနေပြီးတဲ့နောက် ကယ်ထုတ်တဲ့အချိန်တုန်းက တယောက်ကို ကိုယ်အလေးချိ်န် ပျှမ်းမျှခြင်း ၉ ပေါင်စီလောက် ကျသွားကြပေမဲ့ ဆေးရုံတက် ကုသမှုခံယူပြီးတဲ့နောက် ၆ ပေါင်ခွဲစီ ပြန်တက်လာပြီလို့လည်း ဆရာဝန်တွေကပြောပါတယ်။  

- မနက်ဖန်တနင်္ဂနွေနေ့မှာတော့ ရုရှားသမ္မတပူတင်နဲ့ တွေ့ဆုံ ဖို့ ဖင်လန်နိုင်ငံကို သွားရောက်မှာ ပါ။၃ ရက် ကြာ ခရီးစဉ်အဖြစ် ဗြိ<span style="color:red">တိ်န်နိ်ုင်</span>ငံကို ရောက်နေတဲ့ သမ္မတ ထရမ့်ဟာ ဒီကနေ့မှာတော့ စကော့တလန်ကို ရောက်ရှိနေပြီး အဲဒီမှာ သူ့ကို ဆန့်ကျင်သူတွေက ကန့်ကွက်ဆန္ဒပြနေကြပါတယ်။  

- အိုင်အက်<span style="color:red">စ</span> အဖွဲ့ က အဲဒါသူတို့လက်ချက်လို့ ကြေညာထားပါတယ်။  

- မစ္စတာ ရှာရစ်ဖ် ကို လာဟိုး လေဆိပ်ဆင်းလာကတည်း က အာဏာပိုင်တွေ က ဖမ်းခဲ့ပြီး မြို့တော် အစ္စလာမ်မာဘတ်<span style="color:red">စ</span> ကို ခေါ်သွားမယ့် အထူးလေယာဉ်ပေါ်ကို ပြောင်းတင် ပေးခဲ့ပါတယ်။  

- လှုပ်ရှားနိုင်တုန်းကို ဒေ<span style="color:red">သာ</span>ရသလောက်အတူတူစုစေချင်တယ်။  

- ဆွာဇီလန် ကနေ အက်ဆွာတီးနီ လို့ နာ<span style="color:red">မယ်</span>ပြောင်း

- GPU မှာ run လို့ရ<span style="color:red">အော်</span> လုပ်မှ ဖြစ်လိမ့်မယ်။ 

- သမ္မတ ထရမ့်ကလည်း အီရန်ဟာ သမိုင်းမှာ နာ<span style="color:red">မယ်</span>ဆိုး တွင်ရစ်လိမ့်မယ်လို့ တုံ့ ပြန် ခြိမ်းခြောက်ခဲ့တာ ဖြစ်ပါတယ်။

- သာ<span style="color:red">လီ</span>စွရခိုင်သင်္ကြန် (this is Rakhine language and not a spelling mistake) 

- မြန်မာနိုင်ငံမှာ မိုးတွင်းကာလမှာ တစ်နှစ်ကို ၃ ကြိမ်လောက်ရေကြီးတတ်တဲ့ အတွက် ကျန်တဲ့မိုးတွင်း ကာလတွေမှာ အခုလိုရေထပ်ကြီးမယ်ဆိုရင်တော့ ပျက်<span style="color:red">ဆီး</span>မှု များလာနိုင်သလို ဆန်စပါးတင်ပို့မှုကလည်း ထိခိုက်လာနိုင်တယ်လို့ စိုက်ပျိုးရေးပညာရှင်အချို့က ပြောဆိုပါတယ်။

- ၂၀၁၇ သြဂုတ်လကဖြစ်ပွားခဲ့တဲ့ ရခိုင်ပြည်နယ်မြောက်ပိုင်း ပဋိပက္ခကြောင့် ဘင်္ဂလားဒေ့ရှ်နိုင်ငံဘက် ထွက်ပြေးသွားကြတဲ့ ရိုဟင်ဂျာဒုက္ခသည် (၇)သိန်းတို့ရဲ့ပြဿနာ တနှစ်လောက် ရှိလာချိန်မှာ၊ ဒီပြ<span style="color:red">သ</span>နာကို ရှေ့ဆက်ဘယ်လို ကိုယ်တွယ်ဖြေရှင်းသင့်သလဲ- ဆိုတဲ့ခေါင်းစဉ်နဲ့ အမေရိကန်ပြည်ထောင်စု ဝါရှင်တန်ဒီစီက Heritage Foundation မှာ ဇူလိုင်(၃၀)ရက် မနေ့တုန်းက ဆွေးနွေးပွဲ ကျင်းပခဲ့ပါတယ်။

- နိုင်ငံတော်လှို့ဝှက်ချက်ဥပဒေနဲ့ တရားရုံးမှာ စွဲချက်တင် စစ်ဆေးခံနေရတဲ့ Reuter’s သတင်းထောက် ၂ ယောက်ထဲက ကိုကျော်စိုးဦးက သူ့ရဲ့လက်ကိုင်ဖုန်းထဲမှာ ရဲကတွေ့တယ်ဆိုတဲ့ အချက်အလက်တွေ ဘယ်လိုရောက်နေသလဲဆိုတာ သူမသိဘူးလို့ တရားရုံးမှာ တန<span style="color:red">လာ</span>နေ့က ထွက်ဆိုခဲ့ပါတယ်။

- တနင်္လာနေ့က ကြားနာစစ်ဆေးမှုအတွင်း သတင်းထောက်တွေဖမ်းဆီးခံရတဲ့ညက ကားမောင်းလိုက်ပို့ခဲ့<span style="color:red"> တူ</span> Reuter’s သတင်းဌာနရဲ့ ယာဉ်မောင်း ကိုမျိုးသန့်ထွန်းကို သတင်းထောက်တွေရဲ့ရှေ့နေ့က သက်သေအဖြစ်ခေါ်ယူခဲ့ပါတယ်။

- အခုဖွဲ့စည်းလိုက်တဲ့ လွတ်လပ်သော စုံစမ်းရေးကော်မရှင်မှာ ဥက္ကဌအဖြစ် ဖိလစ်ပိုင်နိုင်ငံ ဒုတိယ နိုင်ငံခြားရေးဝန်ကြီးဟောင်းလည်းဖြစ်၊ ကုလသမဂ္ဂ CEDAW ကော်မတီဥက္ကဌဟောင်းလည်းဖြစ်သူ သံအမတ်ကြီး ရိုဆာရီယိုမယ်နာလို Rosario Manalo ကဦးဆောင်ပြီး၊အဖွဲ့ဝင်တွေအဖြစ် ကုလသမဂ္ဂဆိုင်ရာ ဂျပန်အမြဲတမ်း ကိုယ်စားလှယ်ဟောင်းဖြစ်လည်းဖြစ်၊ ကုလသမဂ္ဂ လူသားချင်းစာနာမှု ကိစ္စရပ်များ ဆိုင်ရာ ဒုအတွင်းရေးမှုးချုပ်ဟောင်း သံအမတ်ကြီး ကန်ဇိုအိုရှီးမား Kenzo Oshima ၊ မြန်မာ<span style="color:red">နိ်ုင်</span>ငံ နိုင်ငံတော်ဖွဲ့စည်းပုံ အခြေခံဥပဒေဆိုင်ရာ ခုံရုံးဥက္ကဌဟောင်း ဦးမြသိန်းနဲ့ UNICEF အဆင့်မြင့်အကြံပေးဟောင်းလည်းဖြစ် ကုလသမဂ္ဂဝန်ထမ်းကောလိပ် အဆင့်မြင့်အရာရှိ ဟောင်းလည်းဖြစ်တဲ့ ပါမောက္ခ ဒေါက်တာ အောင်ထွန်းသက်တို့လည်း ပါဝင်ပါတယ်။ 

- နူကလီးယားလက်နက်ဖျက်သိမ်းဖို့သဘောတူထားတဲ့မြောက်ကိုရီးယားရဲ့ ခြေလှမ်းတွေက ဘယ်လိုလဲ ဆိုတာနဲ့ပတ်သက်ပြီး ကိုကျော်အောင်လွင်က တင်ပြပေးထားပါတယ်။ (နြူကလီးယား၊ နူကလီးယားလား ... foreign word ကိစ္စ)

- လူတွေရဲ့ ကျန်းမာရေး အတွက် ပြဿနာတွေရှိလာမှာ၊ ဝမ်းရောဂါတွေဖြစ်လာကြောက်လို့ စခန်းတိုင်းမှာ ကျန်းမာရေးအဖွဲ့တွေထားပေးထားတယ်။ (how to detect this kind of error, let it be ...)

အထက်ပါ အမှားတွေကို အကြမ်းမျဉ်း အုပ်စုခွဲကြည့်ရင် အောက်ပါအတိုင်း    

- Errors because of similar pronunciation
- Typing mistake 
- Language Knowledge 
- Encoding (for us Zawgyi and Unicode font conversion) 
- Foreign word (this is difficult to make a decision) 

I have to find out how many types of spelling mistakes in Myanmar language !!!
I should know percentage (%) of each spelling mistake ... (အချိန်ပေးရလိမ့်မယ်) 
*** English context also consider 

I should understand well on this ... that will help for both spelling error detection and suggestion  
